project_id = "wcpdqskccptsvfandllw"

[auth]
site_url = "http://localhost:5174"
additional_redirect_urls = ["https://lettermelt.vercel.app/**", "http://localhost:5174/**"]
enable_anonymous_sign_ins = true
enable_manual_linking = true

[functions.game]
verify_jwt = true
entrypoint = "./functions/game/index.js"
