project_id = "wcpdqskccptsvfandllw"

[auth]
site_url = "https://lettermelt.com"
additional_redirect_urls = ["https://lettermelt.com/**", "https://www.lettermelt.com/**", "http://localhost:5174/**"]
enable_anonymous_sign_ins = true
enable_manual_linking = true

[functions.game]
verify_jwt = true
entrypoint = "./functions/game/index.js"
